Proposed changes after reading mailing list
zykh/nut pull request #1
Opened 2018-09-03 07:58 UTC by TaorLegrand

Added Static Flags to required data that don't require polling.
Added DEFAULT_ONDELAY / OFFDELAY to load.on.delay / load.off.delay

2018-09-03 22:23 UTC, zykh requested changes

2018-09-03 22:23 UTC, zykh commented on drivers/legrand-hid.c
> +	{ "ups.realpower", 0, 0, "UPS.Output.ConfigActivePower", NULL, "%.0f", HU_FLAG_STATIC, NULL },
is it the nominal power? if so, it should be `ups.realpower.nominal` (also the one below).

2018-09-03 22:23 UTC, zykh commented on drivers/legrand-hid.c
> +	{ "input.transfer.high", 0, 0, "UPS.Input.HighVoltageTransfer", NULL, "%.0f", HU_FLAG_STATIC, NULL },
so, the user is not allowed to change the value of the various `input.transfer.high`/`low` and `battery.charge.low`/`warning` items, right?

2018-09-04 07:28 UTC, TaorLegrand commented on drivers/legrand-hid.c
> +	{ "input.transfer.high", 0, 0, "UPS.Input.HighVoltageTransfer", NULL, "%.0f", HU_FLAG_STATIC, NULL },
Right, it's not allowed

2018-09-04 07:29 UTC, TaorLegrand commented on drivers/legrand-hid.c
> +	{ "ups.realpower", 0, 0, "UPS.Output.ConfigActivePower", NULL, "%.0f", HU_FLAG_STATIC, NULL },
you are right, it's ups.realpower.nominal instead of ups.realpower

2018-09-04 23:05 UTC, zykh approved these changes

2018-09-04 23:07 UTC, merged